name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/upf

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -mpip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -mpip install -r dev-requirements.txt

      - name: MyPy check
        run: python3 -m mypy upf

      - name: Checkout Tamer UPF
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/tamer-upf
          path: tamer-upf
          ref: "52a57fadb69f0908bcf3ea4fb03e7179ebc78732"

      - name: Install Tamer UPF
        run: bash tamer-upf/install.sh

      - name: Download ENHSP
        run: |
          git clone https://gitlab.com/enricos83/ENHSP-Public.git
          cd ENHSP-Public; git checkout enhsp-20; ./compile; cd ..
          mkdir .planners; mv ENHSP-Public/enhsp-dist .planners/enhsp-20; rm -rf ENHSP-Public

      - name: Run tests
        run: bash run_tests.sh

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
