name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/unified-planning

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -m pip install -r dev-requirements.txt

      - name: MyPy check
        run: |
          python3 -m mypy --version
          python3 -m mypy unified_planning

      - name: Checkout Tamer unified-planning interface
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-tamer
          path: up-tamer
          ref: "061b059a2a3b3be7db539a345465d29c510b2574"

      - name: Install Tamer unified-planning interface
        run: python3 -m pip install up-tamer/

      - name: Checkout Pyperplan unified-planning interface
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-pyperplan
          path: up-pyperplan
          ref: "4803ae9f0624d3195e8f6853e3aaf6eda9691bf4"

      - name: Install Pyperplan unified-planning interface
        run: python3 -m pip install up-pyperplan/

      - name: Download ENHSP
        run: |
          git clone https://gitlab.com/enricos83/ENHSP-Public.git
          cd ENHSP-Public; git checkout enhsp-20; ./compile; cd ..
          mkdir .planners; mv ENHSP-Public/enhsp-dist .planners/enhsp-20; rm -rf ENHSP-Public

      - name: Run tests
        run: bash run_tests.sh

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
